## 一、创建 `Tensor`
1.根据函数创建

In [ ]:
import torch
#
# x = torch.empty(3, 5)
# print(x)

In [10]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5604, 0.6829, 0.5211],
        [0.2641, 0.8667, 0.0666],
        [0.6212, 0.8571, 0.6720],
        [0.0360, 0.7886, 0.5415],
        [0.6624, 0.3290, 0.3057]])


In [11]:
x = torch.zeros(2, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


2.根据数据创建(注意数据类型不一致，将自动向上转型)：

In [12]:
x = torch.tensor([5.5, 6])
print(x)

tensor([5.5000, 6.0000])


3.根据现有的 `Tensor` 创建，默认复用原 `Tensor` 的尺寸、数据类型

In [13]:
x = x.new_ones(1, 6, dtype=torch.float64)
y = torch.randn_like(x, dtype=torch.float)

print(x)
print(y)

tensor([[1., 1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-1.5758, -1.3541,  1.4405,  0.8051, -1.6108,  0.5364]])


`Tensor` 的尺寸用 `shape` 或者 `size()` 来获取

In [15]:
print(y.shape)
print(y.size())  # 返回值实质是一个 tuple
print(y.numel())   # 元素个数

torch.Size([1, 6])
torch.Size([1, 6])
6


## 二、操作


1. 算术操作

In [8]:
# 加法形式1
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

# 加法形式2
print(torch.add(x, y))

res = torch.empty(5, 3)
print(torch.add(x, y, out=res))  # 指定输出

# 加法形式3
y.add_(x)  # 原地操作
print(y)

# ※ Pytorch 中所有的原地操作函数名都带 _

tensor([[1.2141, 0.6376, 1.7237],
        [1.4952, 0.9937, 1.2871],
        [0.6542, 1.4554, 0.6929],
        [1.8511, 1.5853, 0.8538],
        [0.8609, 0.8204, 1.2031]])
tensor([[1.2141, 0.6376, 1.7237],
        [1.4952, 0.9937, 1.2871],
        [0.6542, 1.4554, 0.6929],
        [1.8511, 1.5853, 0.8538],
        [0.8609, 0.8204, 1.2031]])
tensor([[1.2141, 0.6376, 1.7237],
        [1.4952, 0.9937, 1.2871],
        [0.6542, 1.4554, 0.6929],
        [1.8511, 1.5853, 0.8538],
        [0.8609, 0.8204, 1.2031]])
tensor([[1.2141, 0.6376, 1.7237],
        [1.4952, 0.9937, 1.2871],
        [0.6542, 1.4554, 0.6929],
        [1.8511, 1.5853, 0.8538],
        [0.8609, 0.8204, 1.2031]])


2. 索引,是原值的引用,数据是共享内存的.

In [9]:
x_sub = x[1:]
x_sub_sub = x[1:3, 1:3]
print(x)
print(x_sub)
print(x_sub_sub)

tensor([[0.5365, 0.6096, 0.7764],
        [0.9763, 0.0651, 0.9785],
        [0.3924, 0.7445, 0.4088],
        [0.9869, 0.8715, 0.1863],
        [0.2719, 0.4114, 0.3044]])
tensor([[0.9763, 0.0651, 0.9785],
        [0.3924, 0.7445, 0.4088],
        [0.9869, 0.8715, 0.1863],
        [0.2719, 0.4114, 0.3044]])
tensor([[0.0651, 0.9785],
        [0.7445, 0.4088]])


In [10]:
# 索引的高级用法
# index_select(input,dim,index) 可选择 input 数据上第 dim 个维度的 index
ind = torch.tensor([0, 2])  # 要求取该维度上前两个元素
a = torch.index_select(x, 1, ind)  # 取前两行
b = torch.index_select(x, 0, ind)  # 取前两列

print(x)
print(a)
print(b)


tensor([[0.5365, 0.6096, 0.7764],
        [0.9763, 0.0651, 0.9785],
        [0.3924, 0.7445, 0.4088],
        [0.9869, 0.8715, 0.1863],
        [0.2719, 0.4114, 0.3044]])
tensor([[0.5365, 0.7764],
        [0.9763, 0.9785],
        [0.3924, 0.4088],
        [0.9869, 0.1863],
        [0.2719, 0.3044]])
tensor([[0.5365, 0.6096, 0.7764],
        [0.3924, 0.7445, 0.4088]])


In [11]:
print(torch.__version__)

1.12.0


 3. 使用 view() 改变 `Tensor`的 `shape`,但是同一份数据

In [12]:
y = x.view(15)
z = x.view(-1, 5)  # -1 表示按照其它维度自动推导
print(x.size(), y.size(), z.size())

print("原 x:\n", x)
y *= 2
print("y*=2 后的 x:\n", x)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
原 x:
 tensor([[0.5365, 0.6096, 0.7764],
        [0.9763, 0.0651, 0.9785],
        [0.3924, 0.7445, 0.4088],
        [0.9869, 0.8715, 0.1863],
        [0.2719, 0.4114, 0.3044]])
y*=2 后的 x:
 tensor([[1.0730, 1.2192, 1.5529],
        [1.9525, 0.1301, 1.9571],
        [0.7849, 1.4891, 0.8176],
        [1.9738, 1.7430, 0.3725],
        [0.5437, 0.8229, 0.6087]])


In [13]:
# 链式依次调用 `clone().view()`,得到真正的一份副本
x_cp = x.clone().view(15)

print("原 x:\n", x)
x_cp -= 10
print("修改了 x_cp 后的x:\n", x)
print("x_cp:\n", x_cp)

原 x:
 tensor([[1.0730, 1.2192, 1.5529],
        [1.9525, 0.1301, 1.9571],
        [0.7849, 1.4891, 0.8176],
        [1.9738, 1.7430, 0.3725],
        [0.5437, 0.8229, 0.6087]])
修改了 x_cp 后的x:
 tensor([[1.0730, 1.2192, 1.5529],
        [1.9525, 0.1301, 1.9571],
        [0.7849, 1.4891, 0.8176],
        [1.9738, 1.7430, 0.3725],
        [0.5437, 0.8229, 0.6087]])
x_cp:
 tensor([-8.9270, -8.7808, -8.4471, -8.0475, -9.8699, -8.0429, -9.2151, -8.5109,
        -9.1824, -8.0262, -8.2570, -9.6275, -9.4563, -9.1771, -9.3913])


4. 转换为 Python 对象:`item()`将一个 `Tensor` 标量转换为一个 `Python Number`

In [14]:
n = torch.randn(1)
print(n)
print(n.item())

tensor([-0.3099])
-0.3099381923675537


5. 堆叠 `Tensor`

In [18]:
sub_1 = torch.arange(12).reshape(3,4)
sub_2 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print(torch.cat((sub_1, sub_2), dim=0))     # 按行堆叠
print(torch.cat((sub_1, sub_2), dim=1))     # 按列堆叠

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## 三、广播机制
前面的都是对同尺寸的 `Tensor` 按元素运算.
当`Tensor`不同尺寸时,可能会触发**广播**机制:
> ①适当复制元素使这两个 `Tensor` 形状相同
> ②将这两个 `Tensor` 按元素运算

In [15]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)

print(x)  # [1*2]
print(y)  # [3*1]

print(x + y)  # [3*2] + [3*2]

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 四、运算的内存开销

如前所述,索引操作是**引用**,而`y = x + y`等算术操作是开辟新内存地址的,即左值`y`和右值`y`实际是不同的内存地址
如果希望算术操作也能写入原地址，可以使用`[:]`操作

In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])

old_id = id(y)
y[:] = y + x
new_id = id(y)
print("Same Memory: ", old_id == new_id)

# 使用 `torch. add_(out=)` 也有相同效果
old_id = id(y)
torch.add(x, y, out=y)
new_id = id(y)
print("Same Memory: ", old_id == new_id)

# 使用 `y.add_(x)` 也有相同效果
old_id = id(y)
y.add_(x)
new_id = id(y)
print("Same Memory: ", old_id == new_id)

Same Memory:  True
Same Memory:  True
Same Memory:  True


## 五、`Tensor` 和 `NumPy` 相互转换

In [19]:
# Tensor -> NumPy : numpy()
# NumPy -> Tensor : from_numpy()
# 注意：两个函数所产生的的 Tensor 和 NumPy 中的数组共享相同的内存
# 所有在 CPU 上的 Tensor（除了 CharTensor）都支持与 NumPy 数组相互转换。

a = torch.ones(5)
na = a.numpy()

print("type(a):",type(a))
print("type(na):",type(na))


a[2] = 10
print(na)  # [ 1.  1. 10.  1.  1.]

type(a): <class 'torch.Tensor'>
type(na): <class 'numpy.ndarray'>
[ 1.  1. 10.  1.  1.]


In [21]:
import numpy as np

nb = np.ones(5)
b = torch.from_numpy(nb)
nb += 3
print(b)

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [22]:
# 复制，而非引用
c = torch.tensor(a)
a += 1
print(a, c)

tensor([ 2.,  2., 11.,  2.,  2.]) tensor([ 1.,  1., 10.,  1.,  1.])


C:\temp\ipykernel_6264\1074872290.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  c = torch.tensor(a)


## 六、Tensor on GPU

In [2]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    # A torch.device is an object representing the device on which a torch.Tensor is or will be allocated.
    device = torch.device("cuda")          # GPU
    x=torch.arange(2<<25)
    y = torch.randn(2<<25, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型


KeyboardInterrupt



In [2]:
torch.cuda.get_device_name()

'NVIDIA GeForce 940MX'

In [7]:
torch.cuda.get_arch_list()

['sm_37',
 'sm_50',
 'sm_60',
 'sm_61',
 'sm_70',
 'sm_75',
 'sm_80',
 'sm_86',
 'compute_37']

In [5]:
import torch
#1.查看gpu信息
print('查看gpu信息：', torch.cuda.is_available())

#GPU的数量
print('GPU的数量：', torch.cuda.device_count())


查看gpu信息： True
GPU的数量： 1


In [6]:
#2.将张量在gpu和cpu间移动
tensor = torch.rand((100, 100))
tensor_gpu = tensor.to('cuda:0') #或者tensor_gpu = tensor.cuda()
print(tensor_gpu.device)
print(tensor_gpu.is_cuda)

tensor_cpu = tensor_gpu.to('cpu') #或者tensor_cpu = tensor_gpu.cpu()
print(tensor_cpu.device)

cuda:0
True
cpu


In [7]:
from torch import nn

#3.将模型中的全部张量移动到gpu上
net = nn.Linear(2,1)
print(next(net.parameters()).is_cuda)
net.to('cuda:0')#将模型中的全部参数张量依次到GPU上，注意，无需重新赋值为net=net.to('cuda:0')
print(next(net.parameters()).is_cuda)
print(next(net.parameters()).device)

False
True
cuda:0


In [8]:
#4.创建支持多个gpu数据并行的模型
linear = nn.Linear(2,1)
print(next(linear.parameters()).device)

model = nn.DataParallel(linear)
print(model.device_ids)
print(next(model.module.parameters()).device)

#注意保存参数时要指定保存model.module的参数
torch.save(model.module.state_dict(), 'model_parameter.pkl')

linear = nn.Linear(2,1)
linear.load_state_dict(torch.load('model_parameter.pkl'))

cpu
[0]
cuda:0


<All keys matched successfully>

In [10]:
#5.清空cuda缓存
#该方在cuda超内存时十分有用
torch.cuda.empty_cache()

## 补充： Pytorch 创建 Tensor 的四种方式的异同
1. torch.Tensor(data)
2. torch.tensor(data)
3. torch.from_numpy(data)
4. torch.as_tensor(data)

In [4]:
import torch
import numpy as np
data = np.array([1, 2, 3])

Tensor = torch.Tensor(data)         # 构造函数，返回值默认为浮点类型       深拷贝
tensor = torch.tensor(data)         # 普通函数，根据输入推断数据类型       深拷贝
from_numpy = torch.from_numpy(data) # 普通函数，根据输入推断数据类型       浅拷贝
as_tensor = torch.as_tensor(data)   # 普通函数，根据输入推断数据类型       浅拷贝

print('输出的结果：')
print(Tensor)
print(tensor)
print(from_numpy)
print(as_tensor)

print('输出的类型：')
print(Tensor.dtype)
print(tensor.dtype)
print(from_numpy.dtype)
print(as_tensor.dtype)

# as_tensor() 更好
# 因为 torch.as_tensor() 可以接受任何 Python 数据结构

输出的结果：
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
输出的类型：
torch.float32
torch.int32
torch.int32
torch.int32
